name: Track-calories

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FATSECRET_APIKEY: ${{ secrets.FATSECRET_APIKEY }}
    environment:
      name: env
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go run . -e FATSECRET_APIKEY